name: C/C++ Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up C++ compiler
      run: sudo apt-get install g++ -y

    - name: Build project
      run: g++ -std=c++17 -Wall -Wextra -o Morphological-Dilation Morphological-Dilation-Project.cpp

    - name: Run tests
      run: ./Morphological-Dilation
